# ansible/inventory/group_vars/staging.yml
---
deploy_path: {{DEPLOY_PATH_STAGING}}
domain: {{DOMAIN_STAGING}}
traefik_insecure: {{TRAEFIK_INSECURE_STAGING}}
disable_https: {{DISABLE_HTTPS_STAGING}}
acme_email: {{ACME_EMAIL}}
acme_server: {{ACME_SERVER_STAGING}}
traefik_users: "{{TRAEFIK_USERS}}"