rulesets:
  - name: "Protect Master Branch"
    target_branches:
      - master
    rules:
      pull_request_rules:
        - type: pull_request
          settings:
            required_reviews: 
              count: 1
            require_last_push_approval: true
      branch_protection:
        required_status_checks:
          strict_required_status_checks: true
        require_code_owner_review: false
        require_last_push_approval: true
        dismisses_stale_reviews: true

  - name: "Develop Branch Workflow"
    target_branches:
      - develop
    rules:
      pull_request_rules:
        - type: pull_request
          settings:
            required_reviews:
              count: 1
      branch_protection:
        required_status_checks:
          strict_required_status_checks: true