services:
  frontend:
    image: ${DOCKERHUB_USERNAME:-mlorentedev}/mlorente-frontend:${TAG:-latest}
    restart: always
    ports:
      - "3000:4321"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: ${DOCKERHUB_USERNAME:-mlorentedev}/mlorente-backend:${TAG:-latest}
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge