services:
  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - backend

  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/tmp
    env_file:
      - .env.dev

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

networks:
  default:
    name: mlorente-dev