services:
  frontend:
    container_name: mlorente-staging-frontend
    image: mlorentedev/mlorente-frontend:develop
    ports:
      - "4001:4321"
    environment:
      - HOST=0.0.0.0      
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: mlorente-staging-backend
    image: mlorentedev/mlorente-backend:develop
    ports:
      - "4002:8080"
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    container_name: mlorente-staging-nginx
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
