tls:
  options:
    default:
      minVersion: {{TLS_MIN_VERSION}}
      cipherSuites:
        - {{TLS_CIPHER_SUITE_1}}
        - {{TLS_CIPHER_SUITE_2}}
        - {{TLS_CIPHER_SUITE_3}}
        - {{TLS_CIPHER_SUITE_4}}
        - {{TLS_CIPHER_SUITE_5}}
        - {{TLS_CIPHER_SUITE_6}}
  domains:
  - main: "mlorente.dev"
    sans:
      - "*.mlorente.dev"
      - "traefik.mlorente.dev"