services:
  traefik-proxy:
    image: traefik:v2.11
    container_name: traefik-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./acme.json:/acme.json"
      - "./dynamic_conf:/etc/traefik/dynamic_conf"
      - "./logs:/var/log/traefik"       
      - "./ssl/certs/default.crt:/etc/ssl/certs/default.crt"
      - "./ssl/private/default.key:/etc/ssl/private/default.key"
    env_file:
      - .env  
    #command:
    #  - "--global.checkNewVersion=true"
    #  - "--global.sendAnonymousUsage=false"
    #  - "--api.dashboard=${TRAEFIK_DASHBOARD:-true}"
    #  - "--api.insecure=${INSECURE:-false}"
    #  - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
    #  - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    #  - "--certificatesresolvers.myresolver.acme.caServer=${SERVER}"
    #  - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
    labels:
      - "traefik.enable=true"
      # Allow ACME HTTP Challenge
      - "traefik.http.routers.acme-http-solver.rule=PathPrefix(`/.well-known/acme-challenge/`)"
      - "traefik.http.routers.acme-http-solver.entrypoints=web"
      - "traefik.http.routers.acme-http-solver.priority=100"
      # Middleware for basic auth
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_USERS}"
    networks:
      - traefik_network 

networks:
  traefik_network:
    name: traefik_network
    external: true
