services:
  jekyll-production:
    image: "${DOCKERHUB_USERNAME}/${ARTIFACT_NAME}:${ENVIRONMENT}-latest"
    container_name: jekyll-production
    restart: always
    expose:
      - "4000"
    env_file:
      - .env   
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jekyll-production.loadbalancer.server.port=4000"
    networks:
      - traefik_network

networks:
  traefik_network:
    name: traefik_network
    external: true
