# ansible/playbooks/setup.yml
---
- name: Server initial setup
  hosts: "{{ env }}"
  become: true
  
  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
          - jq
        state: present
        update_cache: yes
      become: true      

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker and Docker-compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present
        update_cache: yes
      become: true      

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Reset connection to apply group changes
      meta: reset_connection

    - name: Create Docker network
      community.docker.docker_network:
        name: "{{ docker_network }}"
        state: present

    - name: Configure firewall UFW
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - "22"
        - "80"
        - "443"
        - "8080"

    - name: Enable firewall UFW
      ufw:
        state: enabled
        policy: deny

    - name: Install monitoring tools
      apt:
        name:
          - htop
          - iotop
          - sysstat
          - net-tools
        state: present

    - name: Create Traefik directory
      file:
        path: /opt/traefik
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create deployment directories
      file:
        path: "{{ deploy_path }}/{{ item }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      with_items:
        - backups
        - core/infrastructure/docker-compose
        - traefik