name: Check branch name

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!master'      

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check branch name
        run: |
          branch_name=$(git symbolic-ref --short HEAD)
          if [[ ! "$branch_name" =~ ^(feature|hotfix)/.* ]]; then
              echo "Error: Branch name must start with 'feature/' or 'hotfix/'."
              exit 1
          fi