name: Frontend CI

on:
  push:
    branches: [master, develop, "feature/*", "hotfix/*"]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
      - 'docker/frontend/**'
  pull_request:
    branches: [master, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
      - 'docker/frontend/**'

jobs:
  lint-and-type-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Prepare setup
        working-directory: frontend
        run: |
          if [ -f .env ]; then
            echo "Using existing .env file"
          else
            echo "Creating .env file from .env.example"
            mv .env.example .env
          fi
      
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Lint code
        working-directory: frontend
        run: npm run lint

      - name: Format code
        working-directory: frontend
        run: npm run format
      
      - name: Type check
        working-directory: frontend
        run: npm run astro check
  build:
    name: Build Frontend
    needs: lint-and-type-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist
          retention-days: 7
  docker:
    name: Build Docker Image
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist

      - name: Extract metadata and tag
        id: meta
        run: |
          # Configure version and tags
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "VERSION=latest" >> $GITHUB_ENV
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "VERSION=develop" >> $GITHUB_ENV
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" =~ ^refs/heads/feature/.+ ]]; then
            # Extract feature name
            FEATURE_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/feature/||')
            echo "VERSION=feature-${FEATURE_NAME}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" =~ ^refs/heads/hotfix/.+ ]]; then
            # Extract hotfix name
            HOTFIX_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/hotfix/||')
            echo "VERSION=hotfix-${HOTFIX_NAME}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlorente-frontend:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mlorente-frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mlorente-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mlorente-frontend:buildcache,mode=max