name: Frontend CI

on:
  push:
    branches: [master, develop, "feature/*", "hotfix/*"]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - 'docker/frontend/**'
  pull_request:
    branches: [master, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - 'docker/frontend/**'

env:
  REGISTRY: docker.io
  FRONTEND_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mlorente-frontend

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Lint
        run: |
          cd frontend
          npm run lint
      
      - name: Type check
        run: |
          cd frontend
          npm run astro check

  build-frontend:
    needs: test-frontend
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        run: |
          # Configure version and tags
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "VERSION=latest" >> $GITHUB_ENV
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "VERSION=develop" >> $GITHUB_ENV
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" =~ ^refs/heads/feature/.+ ]]; then
            # Extract feature name
            FEATURE_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/feature/||')
            echo "VERSION=feature-${FEATURE_NAME}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" =~ ^refs/heads/hotfix/.+ ]]; then
            # Extract hotfix name
            HOTFIX_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/hotfix/||')
            echo "VERSION=hotfix-${HOTFIX_NAME}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi
      
      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.FRONTEND_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.FRONTEND_IMAGE_NAME }}:buildcache,mode=max
      
      - name: Trigger deployment
        if: success() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: trigger-deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "component": "frontend", "env": "${{ env.DEPLOY_ENV }}", "version": "${{ env.VERSION }}"}'